### ISSUE TITLE
Does not work with URL with parameters.

### ISSUE THREAD

**Issue by mikunimaru** [chase-moskal/webp-hero#22] opened 2019-05-14 14:21 UTC
It does not detect URL with parameter, for example 
"https://chasemoskal.com/webp-hero/images/dice.webp?foo".

**Comment by chase-moskal** [comment] 2019-05-15 21:30
thank you for reporting this issue :)

next we need to

- [x] identify the cause of this bug
  the regex in webp-machine on image src was too restrictive
- [x] launch a pull request which implements a fix
- [x] merge the pr

contributions welcome

**Comment by chase-moskal** [comment] 2019-05-28 18:25
@Lobasya — thanks for contributing on this issue

there was an error with your pull request, so i closed #24 

we really want to receive your contributions, so hopefully you can post a new pull request, or perhaps explain any findings about the root cause of the bug in this issue

thanks :wave:

**Comment by chase-moskal** [comment] 2019-05-31 19:14
this bug has been fixed in `webp-hero@0.0.0-dev.23`

**Closed as completed** 2019-05-31 19:13 UTC
Labels: bug, help wanted, good first issue
