### ISSUE TITLE
Should this work for Base64 encoded Webp?

### ISSUE THREAD

**Issue by Nantris** [chase-moskal/webp-hero#27] opened 2019-08-30 18:23 UTC
No matter what I've tried, I always get the missing image icon on Safari for Mac and iOS. It works fine if I link to a file. Is there some way to leverage this awesome module for use with Base64 images as it currently exists, or is some PR required?

**Comment by Nantris** [comment] 2019-09-02 21:41
@chase-moskal - I'm working on this issue, but when bundling I'm getting this error:

```
 browserify dist-cjs/webp-hero.bundle.js -p tinyify -o dist-cjs/webp-hero.bundle.js
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:333541) while parsing C:\projects\myProject\packages\shared\webp-hero\libwebp\dist\webp.js while parsing file: C:\projects\myProject\packages\shared\webp-hero\libwebp\dist\webp.js
```

[This seems to be the solution](https://stackoverflow.com/a/40029232/6025788), but I don't want to depart wildly from what you've already setup so I can submit a PR without including a rebuild of the compiler workflow.

**Comment by chase-moskal** [comment] 2019-09-03 22:07
hello @Slapbox,

## first, let's look at the base64 situation:

1. does webp-hero currently work to polyfill base64 encoded images?
    - not yet
2. what does webp-hero currently support for polyfilling?
    - old fashioned image elements, such as `<img src="pic.jpg" alt=""/>`
    - nothing else
3. what is *not yet* supported by webp-hero, but would desirable enhancements?
    - base64 encoded data-uri's (both for img elements, and also css images)
    - css images (background-image, in document stylesheets, and inline-styles)
    - `<picture>` elements
4. how can we enhance webp-hero to support base64 images?
    - in [source/webp-machine.ts](https://github.com/chase-moskal/webp-hero/blob/master/source/webp-machine.ts#L62), we'd want to enhance the `polyfillImage` method
    - how it currently works
      - this method takes in an `<img>` element, loads the webp binary data with an http request for the `src` uri, and decodes that binary data into a base64 png data uri which is set as the `<img>` element's new `src`
      - so the image's `src` is actually overridden with the decoded png as a base64 data uri
    - what changes are needed
      - the change would be to inspect the `src` and check if it's a webp base64 data uri, and if so, convert the base64 data into binary data (an arraybuffer) that can be fed into the `decode` method
      - so, if the image src is a base64 webp, we'd decode the base64 and pass that to decode, instead of loading the binary data from an http request as is currently done
    - what requirements must be met
      - the caching needs to still work for base64 images too

## next, let's look at the bundling issue

- first, let me be clear -- during development of webp-hero, you should *not* run the bundle command on it's own -- especially because it actually overwrites the "bundle source" in-place.. it's a little weird that way
- when developing webp-hero, after you make any changes, you should **simply run `npm install` everytime to run a full build**

are you getting this error when using `npm install` in the webp-hero project?

the webp-hero build includes the command `replace 'libwebp\\/dist\\/webp\\.js' 'libwebp/dist/webp.cjs.js' dist-cjs/webp-machine.js` -- that command rewrites an import, and if this command didn't work on your system, i could imagine it might cause the error you're seeing

i notice you're on windows, whereas i'm on linux, so perhaps a utility like `replace` isn't cross-platform like i was hoping?

hopefully we can figure this out together, and it would be great if you could provide a PR which enables the polyfilling of base64 encoded images!

to open source, cheers! :beers:

**Comment by chase-moskal** [comment] 2019-09-03 22:15
fyi, i just pushed a commit on master, just updating all of the npm dependencies :+1:

**Comment by Nantris** [comment] 2019-09-06 16:57
@chase-moskal thanks a ton for this great info! I'm bouncing around between a lot of tasks, but I'll revisit this soon and this should definitely be enough information to start making headway.

**Comment by binarypie** [comment] 2019-12-23 00:15
Is Safari desktop enough to reproduce this error? If so I'll lend a hand.

**Comment by theonetheycallneo** [comment] 2020-04-05 15:24
@chase-moskal @Slapbox Would something like this be acceptable?

feat(decode): adding support for base64 urls #33

**Comment by Nantris** [comment] 2020-04-05 19:25
Sorry, life is too crazy and I never got to come back to this. I don't know what the best way to handle this is, but here's what worked for us:

```js
window.webpMachine = new WebpMachine({
  detectWebpImage: imgEl =>
    /(webp;base64|\.webp.*$)/i.test(imgEl.src),
});
```

**Comment by chase-moskal** [comment] 2020-08-27 05:41
this feature, implemented by @theonetheycallneo, has now been merged to master and published in the latest version of webp-hero. i honestly haven't setup a test for it, i just assume it works!

if anybody experiences any problems with it, please open a new issue!

**Closed as completed by chase-moskal** 2020-08-27 05:41 UTC
Labels: enhancement, question
